export const DEFAULT_CONTROLLER_FEATURES = [
  "DASHBOARD",
  "LIVE_QUIZZES",
  "CREATE_QUIZ",
  "LIVE_ANALYSIS",
  "CONTROL_QUIZ",
  "MANAGE_PARTICIPANTS",
  "MANAGE_RANKINGS",
  "VIEW_RESULTS",
  "MANAGE_LINKS",
] as const;
