import { requireAdmin } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import Link from "next/link";
import { ControllerActivityPanel } from "@/components/ControllerActivityPanel";

export default async function ControllerDetails({ params }: { params: Promise<{ id: string }> }) {
  await requireAdmin();
  const { id } = await params;
  const controller = await prisma.user.findUnique({ where: { id, role: "CONTROLLER" }, include: { createdQuizzes: { include: { _count: { select: { questions: true, attempts: true } } }, orderBy: { createdAt: "desc" } }, assignedTasks: { orderBy: { createdAt: "desc" } }, auditLogs: { select: { id: true, action: true, details: true, timestamp: true, targetId: true, undoData: true, undoneAt: true }, orderBy: { timestamp: "desc" }, take: 100 } } });
  if (!controller) return <main className="p-8">Controller not found.</main>;
  const createdCount = controller.createdQuizzes.length;
  const liveCount = controller.createdQuizzes.filter((quiz) => ["RUNNING", "PAUSED"].includes(quiz.runtimeStatus)).length;
  const completedCount = controller.createdQuizzes.filter((quiz) => ["COMPLETED", "STOPPED"].includes(quiz.runtimeStatus)).length;
  const quizIds = controller.auditLogs.filter((activity) => activity.action.startsWith("QUIZ_") && activity.targetId).map((activity) => activity.targetId!);
  const existingQuizIds = new Set((await prisma.quiz.findMany({ where: { id: { in: quizIds } }, select: { id: true } })).map((quiz) => quiz.id));
  const activities = controller.auditLogs.map((activity) => ({ ...activity, quizExists: !activity.action.startsWith("QUIZ_") || existingQuizIds.has(activity.targetId || ""), timestamp: activity.timestamp.toISOString(), undoneAt: activity.undoneAt?.toISOString() || null }));
  return <main className="min-h-screen bg-slate-50 p-6"><div className="max-w-5xl mx-auto space-y-6"><Link href="/admin/controllers" className="text-amber-700 hover:underline">Back to controllers</Link><section className="bg-white border rounded-xl p-6"><h1 className="text-2xl font-bold">{controller.name}</h1><p className="text-slate-600">QuizNexa ID: {controller.quiznexaId || "Not assigned"}</p><p className="mt-3 text-sm">Status: <b className="text-emerald-700">{controller.isControllerVerified ? "Approved" : "Pending"}</b></p></section><section className="grid gap-4 sm:grid-cols-3"><div className="rounded-xl border bg-white p-5"><p className="text-sm text-slate-500">Quizzes created</p><p className="mt-1 text-3xl font-bold">{createdCount}</p></div><div className="rounded-xl border bg-white p-5"><p className="text-sm text-slate-500">In progress / live</p><p className="mt-1 text-3xl font-bold text-emerald-700">{liveCount}</p></div><div className="rounded-xl border bg-white p-5"><p className="text-sm text-slate-500">Done / completed</p><p className="mt-1 text-3xl font-bold text-blue-700">{completedCount}</p></div></section><ControllerActivityPanel activities={activities} /><section className="bg-white border rounded-xl p-6"><h2 className="font-semibold mb-4">Created quizzes</h2>{controller.createdQuizzes.map(quiz => <div key={quiz.id} className="border-b py-3 flex justify-between"><span>{quiz.title}</span><span className="text-sm text-slate-500">{quiz.runtimeStatus} · {quiz._count.questions} questions · {quiz._count.attempts} attempts</span></div>)}</section><section className="bg-white border rounded-xl p-6"><h2 className="font-semibold mb-4">Assigned tasks</h2>{controller.assignedTasks.length ? controller.assignedTasks.map(task => <div key={task.id} className="border-b py-3 flex justify-between"><span>{task.title}</span><span className="text-sm text-slate-500">{task.status}</span></div>) : <p className="text-slate-500">No tasks assigned.</p>}</section></div></main>;
}
