"use client";

import { useEffect, useRef, useState } from "react";
import { Activity, BarChart3, CheckCircle2, Clock3, Medal, Users } from "lucide-react";
import { QuizLinkPanel } from "@/components/QuizLinkPanel";
import type { LucideIcon } from "lucide-react";

type MonitorData = {
  quiz: { title: string; runtimeStatus: string; durationMinutes: number; totalQuestions: number; quizType: string; presentationMode: string };
  summary: { totalParticipants: number; activeParticipants: number; submittedParticipants: number; averageScore: number; completionRate: number };
  participants: { id: string; rank: number | null; name: string; email: string | null; score: number; answered: number; correctAnswers: number; totalTimeSeconds: number; averageTimePerQuestion: number; submitted: boolean; disqualified: boolean; state: string; teamMembers: { user: { name: string; email: string } }[] }[];
  notJoined: { id: string; name: string; email: string | null; status: string; joinedAt: string }[];
  earlyLeaves: { id: string; name: string; email: string | null; answered: number; correctAnswers: number; progress: number; score: number; rank: number | null; leftAt: string }[];
  submittedParticipants: { id: string; name: string; email: string | null; answered: number; correctAnswers: number; progress: number; score: number; rank: number | null; submittedAt: string }[];
  questionAnalytics: { number: number; text: string; options: string[]; correctAnswer: string; answers: number; correct: number; accuracy: number }[];
  generatedAt: string;
};

export function QuizMonitor({ quizId, backHref }: { quizId: string; backHref: string }) {
  const [data, setData] = useState<MonitorData | null>(null);
  const [tab, setTab] = useState<"overview" | "participants" | "notJoined" | "early" | "submitted" | "correct" | "questions">("overview");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const requestInFlight = useRef(false);
  const load = async () => { if (requestInFlight.current) return; requestInFlight.current = true; setError(""); try { const response = await fetch(`/api/quizzes/${quizId}/monitor?refresh=${Date.now()}`, { cache: "no-store" }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(result.error || "Unable to refresh live analysis"); setData(result); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Unable to refresh live analysis"); } finally { setLoading(false); requestInFlight.current = false; } };
  useEffect(() => { load(); const timer = window.setInterval(() => { if (document.visibilityState === "visible") void load(); }, 5000); return () => window.clearInterval(timer); }, [quizId]);

  if (loading || !data) return <main className="min-h-screen bg-slate-50 p-6"><div className="max-w-6xl mx-auto">Loading live analysis...</div></main>;
  const tabs = [{ id: "overview", label: "Overview", icon: Activity }, { id: "participants", label: "Participants", icon: Users }, { id: "notJoined", label: "Not joined", icon: Clock3 }, { id: "early", label: "Early leave", icon: Clock3 }, { id: "submitted", label: "Submitted", icon: CheckCircle2 }, { id: "questions", label: "Questions", icon: BarChart3 }] as const;
  const metrics: Array<[string, string | number, LucideIcon]> = [["Participants", data.summary.totalParticipants, Users], ["In progress", data.summary.activeParticipants, Clock3], ["Submitted", data.summary.submittedParticipants, CheckCircle2], ["Average score", `${data.summary.averageScore}%`, BarChart3], ["Completion", `${data.summary.completionRate}%`, Medal]];
  return <main className="min-h-screen bg-[#f5f7f6] p-4 sm:p-6"><div className="max-w-6xl mx-auto space-y-5">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><a href={backHref} className="text-sm text-emerald-700 hover:underline">Back</a><h1 className="text-2xl sm:text-3xl font-bold text-slate-900 mt-2">{data.quiz.title}</h1><div className="flex flex-wrap gap-2 mt-2 text-xs text-slate-500"><span className="px-2 py-1 rounded-full bg-white border">{data.quiz.runtimeStatus}</span><span className="px-2 py-1 rounded-full bg-white border">{data.quiz.quizType}</span><span className="px-2 py-1 rounded-full bg-white border">Updated {new Date(data.generatedAt).toLocaleTimeString()}</span></div></div></header>
    {!(["STOPPED", "COMPLETED"] as string[]).includes(data.quiz.runtimeStatus) && <QuizLinkPanel quizId={quizId} />}
    {error && <p role="alert" className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    <nav className="min-w-0 max-w-full overflow-x-auto overscroll-x-contain rounded-xl border bg-white p-1 touch-pan-x"><div className="flex min-w-max gap-1">{tabs.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => setTab(id)} className={`inline-flex shrink-0 items-center gap-2 whitespace-nowrap rounded-lg px-4 py-2 text-sm font-medium ${tab === id ? "bg-slate-900 text-white" : "text-slate-600 hover:bg-slate-100"}`}><Icon size={16}/>{label}</button>)}</div></nav>
    <section className="grid grid-cols-2 lg:grid-cols-5 gap-3">{metrics.map(([label, value, Icon]) => <div key={label} className="bg-white rounded-xl border p-4"><Icon className="text-emerald-600 mb-3" size={19}/><p className="text-xs text-slate-500">{label}</p><p className="text-2xl font-bold text-slate-900 mt-1">{value}</p></div>)}</section>
    {tab === "overview" && <section className="bg-white rounded-xl border p-5"><h2 className="font-semibold text-slate-900 mb-4">Live activity</h2><div className="h-3 rounded-full bg-slate-100 overflow-hidden"><div className="h-full bg-emerald-500 transition-all" style={{ width: `${data.summary.completionRate}%` }}/></div><div className="mt-4 grid sm:grid-cols-3 gap-4 text-sm"><p><span className="text-slate-500">Mode</span><br/><b>{data.quiz.presentationMode}</b></p><p><span className="text-slate-500">Duration</span><br/><b>{data.quiz.durationMinutes} minutes</b></p><p><span className="text-slate-500">Questions</span><br/><b>{data.quiz.totalQuestions}</b></p></div></section>}
    {tab === "participants" && <section className="bg-white rounded-xl border overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="p-4">Rank</th><th className="p-4">Participant / team</th><th className="p-4">Progress</th><th className="p-4">Correct answers</th><th className="p-4">Score</th><th className="p-4">Average time</th><th className="p-4">State</th></tr></thead><tbody>{data.participants.flatMap((participant) => { const people = participant.teamMembers.length ? participant.teamMembers : [{ user: { name: participant.name, email: participant.email || "" } }]; return people.map((member, index) => <tr key={`${participant.id}-${index}`} className="border-t"><td className="p-4 font-semibold">{participant.rank ? `#${participant.rank}` : "-"}</td><td className="p-4"><p className="font-medium">{member.user.name}{participant.teamMembers.length ? ` (${participant.name})` : ""}</p><p className="text-xs text-slate-500">{member.user.email}</p></td><td className="p-4">{participant.answered} / {data.quiz.totalQuestions}</td><td className="p-4 font-semibold text-emerald-700">{participant.correctAnswers}</td><td className="p-4 font-semibold">{participant.score}%</td><td className="p-4">{participant.averageTimePerQuestion}s</td><td className="p-4"><span className={`rounded-full px-2 py-1 text-xs ${participant.disqualified ? "bg-red-100 text-red-700" : participant.state === "Submitted" ? "bg-emerald-100 text-emerald-700" : participant.state === "In progress" ? "bg-blue-100 text-blue-700" : "bg-amber-100 text-amber-700"}`}>{participant.disqualified ? "Disqualified" : participant.state}</span></td></tr>); })}</tbody></table></div></section>}
    {tab === "questions" && <section className="space-y-3">{data.questionAnalytics.map((question) => <div key={question.number} className="bg-white rounded-xl border p-4"><div className="flex justify-between gap-4"><div><p className="font-medium text-slate-900">Q{question.number}. {question.text}</p><p className="mt-1 text-xs text-slate-500">Answered by {question.answers} students · Solved correctly by {question.correct} students</p></div><b className="shrink-0 text-emerald-700">{question.accuracy}%</b></div><div className="mt-3 space-y-2">{question.options.map((option) => <div key={option} className={`rounded-lg border px-3 py-2 text-sm ${option === question.correctAnswer ? "border-emerald-300 bg-emerald-50 font-semibold text-emerald-800" : "border-slate-200 bg-slate-50 text-slate-700"}`}>{option}{option === question.correctAnswer && <span className="ml-2 text-xs">(Correct)</span>}</div>)}</div><div className="mt-3 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-500" style={{ width: `${question.accuracy}%` }}/></div></div>)}</section>}
    {tab === "early" && <section className="bg-white rounded-xl border overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="p-4">Participant</th><th className="p-4">Questions submitted</th><th className="p-4">Correct answers</th><th className="p-4">Left after</th><th className="p-4">Progress</th><th className="p-4">Score</th><th className="p-4">Rank</th></tr></thead><tbody>{data.earlyLeaves.length ? data.earlyLeaves.map((participant) => <tr key={participant.id} className="border-t"><td className="p-4"><p className="font-medium">{participant.name}</p><p className="text-xs text-slate-500">{participant.email || ""}</p></td><td className="p-4">{participant.answered}</td><td className="p-4 font-semibold text-emerald-700">{participant.correctAnswers}</td><td className="p-4">{participant.answered} question{participant.answered === 1 ? "" : "s"}</td><td className="p-4">{participant.progress}%</td><td className="p-4 font-semibold">{participant.score}%</td><td className="p-4">{participant.rank ? `#${participant.rank}` : "-"}</td></tr>) : <tr><td colSpan={7} className="p-6 text-center text-slate-500">No students left early.</td></tr>}</tbody></table></div></section>}
    {tab === "notJoined" && <section className="bg-white rounded-xl border overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="p-4">Participant</th><th className="p-4">Status</th><th className="p-4">Joined at</th></tr></thead><tbody>{data.notJoined.length ? data.notJoined.map((participant) => <tr key={participant.id} className="border-t"><td className="p-4"><p className="font-medium">{participant.name}</p><p className="text-xs text-slate-500">{participant.email || ""}</p></td><td className="p-4">{participant.status.replaceAll("_", " ")}</td><td className="p-4">{new Date(participant.joinedAt).toLocaleString()}</td></tr>) : <tr><td colSpan={3} className="p-6 text-center text-slate-500">No students waiting to join.</td></tr>}</tbody></table></div></section>}
    {tab === "submitted" && <section className="bg-white rounded-xl border overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="p-4">Rank</th><th className="p-4">Participant</th><th className="p-4">Questions submitted</th><th className="p-4">Correct answers</th><th className="p-4">Progress</th><th className="p-4">Score</th><th className="p-4">Submitted at</th></tr></thead><tbody>{data.submittedParticipants.length ? data.submittedParticipants.map((participant) => <tr key={participant.id} className="border-t"><td className="p-4 font-semibold">{participant.rank ? `#${participant.rank}` : "-"}</td><td className="p-4"><p className="font-medium">{participant.name}</p><p className="text-xs text-slate-500">{participant.email || ""}</p></td><td className="p-4">{participant.answered}</td><td className="p-4 font-semibold text-emerald-700">{participant.correctAnswers}</td><td className="p-4">{participant.progress}%</td><td className="p-4 font-semibold">{participant.score}%</td><td className="p-4">{new Date(participant.submittedAt).toLocaleString()}</td></tr>) : <tr><td colSpan={7} className="p-6 text-center text-slate-500">No students have submitted the quiz.</td></tr>}</tbody></table></div></section>}
    {tab === "correct" && <section className="bg-white rounded-xl border overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="p-4">Rank</th><th className="p-4">Participant / team</th><th className="p-4">Correct answers</th><th className="p-4">Questions answered</th><th className="p-4">Score</th><th className="p-4">State</th></tr></thead><tbody>{data.participants.flatMap((participant) => { const people = participant.teamMembers.length ? participant.teamMembers : [{ user: { name: participant.name, email: participant.email || "" } }]; return people.map((member, index) => <tr key={`${participant.id}-${index}`} className="border-t"><td className="p-4 font-semibold">{participant.rank ? `#${participant.rank}` : "-"}</td><td className="p-4"><p className="font-medium">{member.user.name}{participant.teamMembers.length ? ` (${participant.name})` : ""}</p><p className="text-xs text-slate-500">{member.user.email}</p></td><td className="p-4 font-semibold text-emerald-700">{participant.correctAnswers}</td><td className="p-4">{participant.answered}</td><td className="p-4">{participant.score}%</td><td className="p-4">{participant.state}</td></tr>); })}</tbody></table></div></section>}
  </div></main>;
}