"use client";

import { useEffect, useRef, useState } from "react";
import { Trash2 } from "lucide-react";
import { BookOpen } from "lucide-react";
import { PlatformMessage } from "@/components/PlatformMessage";

export function QuizLinkPanel({ quizId }: { quizId: string }) {
  const [links, setLinks] = useState<{ id: string; shareLink: string; qrCodeData: string | null; expiresAt: string | null; maxStudents: number | null }[]>([]);
  const [maxStudents, setMaxStudents] = useState("");
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  const loadInFlight = useRef(false);
  const load = async () => { if (loadInFlight.current) return; loadInFlight.current = true; try { const response = await fetch(`/api/quizzes/${quizId}/generate-link`, { cache: "no-store" }); if (response.ok) setLinks((await response.json()).links); } finally { loadInFlight.current = false; } };
  useEffect(() => { void load(); const timer = window.setInterval(() => { if (document.visibilityState === "visible") void load(); }, 5000); return () => window.clearInterval(timer); }, [quizId]);
  const generate = async () => { setBusy(true); setMessage(""); try { const response = await fetch(`/api/quizzes/${quizId}/generate-link`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ maxStudents: maxStudents ? Number(maxStudents) : null }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to generate link"); setLinks(current => [data.quizLink, ...current]); setMessage("Join link and QR code generated."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to generate link"); } finally { setBusy(false); } };
  const remove = async (linkId: string) => { setBusy(true); setMessage(""); try { const response = await fetch(`/api/quizzes/${quizId}/generate-link`, { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ linkId }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to delete link"); setLinks(current => current.filter(link => link.id !== linkId)); setMessage("Join link deleted."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to delete link"); } finally { setBusy(false); } };
  return <section className="rounded-lg border bg-white p-5"><h2 className="font-bold">Student access</h2><div className="mt-3 flex flex-wrap gap-2"><input type="number" min="1" value={maxStudents} onChange={event => setMaxStudents(event.target.value)} placeholder="Optional student limit" className="rounded border px-3 py-2" /><button disabled={busy} onClick={generate} className="rounded bg-slate-900 px-4 py-2 font-medium text-white disabled:opacity-60">{busy ? "Generating..." : "Generate link & QR"}</button></div>{message && <div className="mt-3"><PlatformMessage message={message} tone={message.includes("Unable") ? "error" : "success"} /></div>}<div className="mt-4 space-y-3">{links.map(link => <div key={link.id} className="flex flex-wrap items-center gap-4 rounded border p-3"><div className="min-w-0 flex-1"><a href={link.shareLink} target="_blank" rel="noreferrer" className="break-all text-sm text-emerald-700 underline">{link.shareLink}</a><p className="text-xs text-slate-500">Expires {link.expiresAt ? new Date(link.expiresAt).toLocaleString() : "never"}</p></div>{link.qrCodeData && <div className="relative h-24 w-24 shrink-0 rounded border bg-white p-1"><img src={link.qrCodeData} alt="QuizNexa quiz join QR code" className="h-full w-full" /><span className="absolute left-1/2 top-1/2 flex h-7 w-7 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-md border-2 border-white bg-[#e5a83b] text-[#172a2d] shadow-sm"><BookOpen size={16} strokeWidth={2.5} /></span></div>}<button type="button" title="Delete join link" aria-label="Delete join link" disabled={busy} onClick={() => remove(link.id)} className="rounded p-2 text-red-600 hover:bg-red-50 disabled:opacity-60"><Trash2 className="h-5 w-5" /></button></div>)}</div></section>;
}
